$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python3 train.py 
  --training_data ${{inputs.training_data}} 
  --reg_rate 0.01
inputs:
  training_data: 
    type: uri_folder 
    path: azureml:diabetes-prod-folder:1
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:ayumulcompute0622
experiment_name: diabetes-experiment-production
description: First Job
