name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  push:
    branches:
    - main 

permissions:
  id-token: write
  contents: read

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Check out repoo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: submit a development job
      run: az ml job create --file src/dev-job.yml --workspace-name mlops-learn-workspace2 --resource-group ayumu.justin.ueda-rg --stream
  

  train-prod:
    runs-on: ubuntu-latest
    needs: [train-dev]
    environment:
      name: production
    steps:
    - name: Check out repoo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: submit a production job
      run: az ml job create --file src/prod-job.yml --workspace-name mlops-learn-workspace2 --resource-group ayumu.justin.ueda-rg --stream


#train-dev

#train-prod

